/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hw6;

import java.awt.Color;
import static java.awt.event.InputEvent.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*;

/**
 *
 * @author Noam
 */
public class HW6Plot extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form HW6Plot
     */
    
    
    
    public HW6Plot() {
        initComponents();
        
        
        jPanel2 = (Plot) jPanel1;
        Plottable2D myFun = new MyFunction();
        jPanel2.setAxis(new double[]{-1, 1, -1, 1});
        jPanel2.setFunction(myFun);
        
        String[] labels = jPanel2.label();
        jLabel1.setText(labels[0]);
        jLabel2.setText(labels[1]);
        jLabel3.setText(labels[2]);
        
        axis = jPanel2.limits();
        jTextField1.setText("" + axis[0]);
        jTextField2.setText("" + axis[1]);
        jTextField3.setText("" + axis[2]);
        jTextField4.setText("" + axis[3]);
        
        jPanel2.addMouseListener(this);
      
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Plot();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Yellow", "Blue" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thickness 1", "Thickness 2", "Thickness 4", "Thickness 8" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(141, 141, 141)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String col = (String) combo.getSelectedItem();
 
        Color c = Color.RED;
        if (col.equals("Green")) {
            c = Color.GREEN;
        } 
        
        else if (col.equals("Blue")) {
            c = Color.BLUE;
        }
        
        else if (col.equals("Red")) {
            c = Color.RED;
        }
        
        else if (col.equals("Yellow")) {
            c = Color.YELLOW;
        }
        
         jPanel2.changeColor(c);             
         jPanel2.repaint();
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String field_2_Value = jTextField2.getText();
        axis[1] = Double.parseDouble(field_2_Value);
        this.setAxis_2();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        String field_4_Value = jTextField4.getText();
        axis[3] = Double.parseDouble(field_4_Value); 
        this.setAxis_2();
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        String field_3_Value = jTextField3.getText();
        axis[2] = Double.parseDouble(field_3_Value); 
        this.setAxis_2();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String field_1_Value = jTextField1.getText();
        axis[0] = Double.parseDouble(field_1_Value);  
        this.setAxis_2();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String col = (String) combo.getSelectedItem();
 
        int t = 1;
        if (col.equals("Thickness 1")) {
            t =1;
        } 
        
        else if (col.equals("Thickness 2")) {
            t=2;
        }
        
        else if (col.equals("Thickness 4")) {
            t=4;
        }
        
        else if (col.equals("Thickness 8")) {
            t=8;
        }
        
         jPanel2.setThickness(t);             
         jPanel2.repaint();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    public void setAxis_2()
    {
        jPanel2.setAxis(axis);
        jPanel2.repaint();
        
    }
    
     public void mousePressed(MouseEvent e) {
                    
                    int x=e.getX();
                    int y=e.getY();
                    
                    x_pressed = x;
                    y_pressed = y;
                    
                    
                    
                    if(x < 0 || x > jPanel2.getWidth() )
                    {
                        //System.out.println("error with x");
                        x_pressed = -1;
                    }
                    else
                    {
                       // System.out.println("x is good");
                    }
                    
                    if(y < 0 || y > jPanel2.getHeight() )
                    {
                        //System.out.println("error with y");
                        y_pressed = -1;
                    }
                    
                    else
                    {
                       // System.out.println("y is good");
                    }
                    
                }

               
               public void mouseReleased(MouseEvent e) {
                
               int x=e.getX();
               int y=e.getY();

               if( x_pressed==-1 || y_pressed == -1)
               {
                   // System.out.println("out of bounds");
               }
               
               else if (x == x_pressed && y == y_pressed) //We need to zoom
               {
                   
                   double xpix_ratio  = (double)x_pressed/jPanel2.getWidth();
                   double ypix_ratio  = 1-(double)y_pressed/jPanel2.getHeight();
                   double a=1;
                   
                   double old_x0 = axis[0];
                   double old_x1 = axis[1];
                   double xaxi_length = old_x1-old_x0;
                   double new_x = (xaxi_length * xpix_ratio)+ old_x0;
                   
                   
                   
                   
                   double old_y0 = axis[2];
                   double old_y1 = axis[3];
                   double yaxi_length = old_y1-old_y0;
                   double new_y = (yaxi_length * ypix_ratio) + old_y0;
                   
                   if(e.getModifiers() == BUTTON1_MASK)
                   {
                       a = 2;
                       
//                        axis[0] =  new_x - ((xaxi_length/1+(xpix_ratio))/2);
//                        axis[1] =  new_x + ((xaxi_length/1+(1-xpix_ratio))/2);
//                        axis[2] =  new_y- ((yaxi_length/1+(ypix_ratio))/2);
//                        axis[3] =  new_y+((yaxi_length/1+(1-ypix_ratio))/2);
                   }
                   
                   else if(e.getModifiers() == BUTTON3_MASK)
                   {
                       a=0.5;
                       
//                        axis[0] = new_x - ((xaxi_length)/2);
//                        axis[1] = new_x + (xaxi_length/2);
//                        axis[2] = new_y - (yaxi_length/2);
//                        axis[3] = new_y + (yaxi_length/2);
                   }
                   
                   
                   axis[0] = -((new_x - old_x0)/a)+new_x; 
                   axis[1] = axis[0]+(xaxi_length/a);
                   axis[2] = -((new_y - old_y0)/a)+new_y;
                   axis[3] = axis[2]+(yaxi_length/a);
                   
                   jTextField1.setText("" + axis[0]);
                   jTextField2.setText("" + axis[1]);
                   jTextField3.setText("" + axis[2]);
                   jTextField4.setText("" + axis[3]);
                   
                   jPanel2.setAxis(axis);
                   jPanel2.repaint();
                   

                      
               }
                    
               else // we need to move the graph
               {
                  
                    
                   double xpix_ratio  = ((double)x-x_pressed)/jPanel2.getWidth();
                   double ypix_ratio  = ((double)y-y_pressed)/jPanel2.getHeight();
                   
                   double old_x0 = axis[0];
                   double old_x1 = axis[1];
                   double xaxi_length = old_x1-old_x0;
                   double new_x = old_x0 - (xaxi_length * xpix_ratio);
                   
                   
                   
                   double old_y0 = axis[2];
                   double old_y1 = axis[3];
                   double yaxi_length = old_y1-old_y0;
                   double new_y =  (yaxi_length * ypix_ratio)+ old_y1 ;
                   
                  
                   
                   axis[0] = new_x ;
                   axis[1] = new_x + (xaxi_length);
                   axis[2] = new_y - (yaxi_length);
                   axis[3] = new_y ;
                   
                   jTextField1.setText("" + axis[0]);
                   jTextField2.setText("" + axis[1]);
                   jTextField3.setText("" + axis[2]);
                   jTextField4.setText("" + axis[3]);
                   
                   jPanel2.setAxis(axis);
                   jPanel2.repaint();
               }
            }
    
    // when right click
    /*
    take the values of the click four axis and  all the values of
    */
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HW6Plot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HW6Plot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HW6Plot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HW6Plot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HW6Plot().setVisible(true);
                
            }
        });
        
        
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    Plot jPanel2;
    double[] axis;
    int x_pressed;
    int y_pressed;
    @Override
    public void mouseClicked(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
